"""units, taxes, category and product pricing overrides

Not one of the 22 phases — added afterwards, at the user's request: a
managed list of units for the "unidad base" picker, a managed list of
taxes (several may apply to one product at once, replacing a single typed
tax_rate), and a margin/taxes default at the category level that a
product's own explicit value overrides. See app.pricing.models's own
module docstring and app.pricing.service.effective_tax_rate/
effective_margin_rate for how the priority is resolved.

Revision ID: 20412e4e301c
Revises: 89da0848671d
Create Date: 2026-08-09 14:12:22.584246+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20412e4e301c"
down_revision: str | None = "89da0848671d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Same example formula app.pricing.formula's own docstring uses — coste +
#: impuesto + recargo, con margen aplicado al final. A real store changes
#: this from the admin panel (Precios → Fórmula) whenever it wants;
#: this is only what a fresh install starts with.
_DEFAULT_FORMULA = (
    "(cost + cost * tax_rate / 100 + cost * surcharge_rate / 100) * (1 + margin_rate / 100)"
)

_pricing_settings = sa.table("pricing_settings", sa.column("formula", sa.Text))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_settings",
        sa.Column("formula", sa.Text(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_settings")),
    )
    op.create_table(
        "taxes",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxes")),
        sa.UniqueConstraint("name", name=op.f("uq_taxes_name")),
    )
    op.create_table(
        "units",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("name", name=op.f("uq_units_name")),
    )
    op.create_table(
        "category_taxes",
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("tax_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.id"],
            name=op.f("fk_category_taxes_category_id_product_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["tax_id"], ["taxes.id"], name=op.f("fk_category_taxes_tax_id_taxes")
        ),
        sa.PrimaryKeyConstraint("category_id", "tax_id", name=op.f("pk_category_taxes")),
    )
    op.create_table(
        "product_taxes",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("tax_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_taxes_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["tax_id"], ["taxes.id"], name=op.f("fk_product_taxes_tax_id_taxes")
        ),
        sa.PrimaryKeyConstraint("product_id", "tax_id", name=op.f("pk_product_taxes")),
    )
    op.add_column(
        "product_categories",
        sa.Column("margin_rate", sa.Numeric(precision=18, scale=6), nullable=True),
    )
    op.alter_column(
        "products",
        "margin_rate",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        server_default=None,
        nullable=True,
    )
    # ### end Alembic commands ###

    op.get_bind().execute(sa.insert(_pricing_settings), [{"formula": _DEFAULT_FORMULA}])


def downgrade() -> None:
    # A product priced after this migration may well have margin_rate NULL
    # (inheriting from its category) — NOT NULL DEFAULT 0 can't go back on
    # top of that without a value, so backfill before re-tightening it.
    op.get_bind().execute(sa.text("UPDATE products SET margin_rate = 0 WHERE margin_rate IS NULL"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "margin_rate",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        server_default=sa.text("'0'::numeric"),
        nullable=False,
    )
    op.drop_column("product_categories", "margin_rate")
    op.drop_table("product_taxes")
    op.drop_table("category_taxes")
    op.drop_table("units")
    op.drop_table("taxes")
    op.drop_table("pricing_settings")
    # ### end Alembic commands ###
