"""ticket_template line_discounts

Revision ID: b660c928adc0
Revises: d110f7909c5b
Create Date: 2026-08-10 15:01:50.363992+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b660c928adc0"
down_revision: str | None = "d110f7909c5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket_templates",
        sa.Column("show_line_discounts", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticket_templates", "show_line_discounts")
    # ### end Alembic commands ###
