"""phase 17: notifications

Revision ID: c6c84b0f03e1
Revises: d39d8f23fa71
Create Date: 2026-08-08 11:40:40.203825+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.rbac.permissions import PHASE_17_PERMISSIONS, PHASE_17_ROLE_GRANTS

revision: str = "c6c84b0f03e1"
down_revision: str | None = "d39d8f23fa71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Lightweight table handles for the seed data below — see the phase 1
# migration for why these aren't the ORM models.
_permissions = sa.table(
    "permissions",
    sa.column("id", sa.BigInteger),
    sa.column("key", sa.String),
    sa.column("description", sa.String),
)
_roles = sa.table("roles", sa.column("id", sa.BigInteger), sa.column("name", sa.String))
_role_permissions = sa.table(
    "role_permissions",
    sa.column("role_id", sa.BigInteger),
    sa.column("permission_id", sa.BigInteger),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_rules",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("rule_type", sa.String(length=30), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_rules")),
    )
    op.create_table(
        "incidents",
        sa.Column("rule_id", sa.BigInteger(), nullable=False),
        sa.Column("subject_type", sa.String(length=30), nullable=False),
        sa.Column("subject_id", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="OPEN", nullable=False),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["notification_rules.id"],
            name=op.f("fk_incidents_rule_id_notification_rules"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index(op.f("ix_incidents_rule_id"), "incidents", ["rule_id"], unique=False)
    op.create_index(
        "uq_incidents_open_subject",
        "incidents",
        ["rule_id", "subject_type", "subject_id"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    # ### end Alembic commands ###

    _seed_permissions()


def _seed_permissions() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.insert(_permissions),
        [{"key": p.key, "description": p.description} for p in PHASE_17_PERMISSIONS],
    )
    permission_ids = dict(
        connection.execute(sa.select(_permissions.c.key, _permissions.c.id)).all()
    )
    role_ids = dict(connection.execute(sa.select(_roles.c.name, _roles.c.id)).all())

    grants = [
        {"role_id": role_ids[role_name], "permission_id": permission_ids[key]}
        for role_name, keys in PHASE_17_ROLE_GRANTS.items()
        for key in keys
    ]
    if grants:
        connection.execute(sa.insert(_role_permissions), grants)


def downgrade() -> None:
    _unseed_permissions()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_incidents_open_subject",
        table_name="incidents",
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.drop_index(op.f("ix_incidents_rule_id"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_table("notification_rules")
    # ### end Alembic commands ###


def _unseed_permissions() -> None:
    connection = op.get_bind()
    keys = [p.key for p in PHASE_17_PERMISSIONS]

    permission_ids = [
        row[0]
        for row in connection.execute(
            sa.select(_permissions.c.id).where(_permissions.c.key.in_(keys))
        ).all()
    ]
    if permission_ids:
        connection.execute(
            _role_permissions.delete().where(_role_permissions.c.permission_id.in_(permission_ids))
        )
        connection.execute(_permissions.delete().where(_permissions.c.id.in_(permission_ids)))
