"""phase 14: returns

Revision ID: 2c00d9c49c90
Revises: 6996851d411a
Create Date: 2026-08-08 10:21:18.967003+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.rbac.permissions import PHASE_14_PERMISSIONS, PHASE_14_ROLE_GRANTS

revision: str = "2c00d9c49c90"
down_revision: str | None = "6996851d411a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Lightweight table handles for the seed data below — see the phase 1
# migration for why these aren't the ORM models.
_permissions = sa.table(
    "permissions",
    sa.column("id", sa.BigInteger),
    sa.column("key", sa.String),
    sa.column("description", sa.String),
)
_roles = sa.table("roles", sa.column("id", sa.BigInteger), sa.column("name", sa.String))
_role_permissions = sa.table(
    "role_permissions",
    sa.column("role_id", sa.BigInteger),
    sa.column("permission_id", sa.BigInteger),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "returns",
        sa.Column("sale_id", sa.BigInteger(), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=False),
        sa.Column("processed_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["processed_by_user_id"],
            ["users.id"],
            name=op.f("fk_returns_processed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(["sale_id"], ["sales.id"], name=op.f("fk_returns_sale_id_sales")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_returns")),
    )
    op.create_index(op.f("ix_returns_sale_id"), "returns", ["sale_id"], unique=False)
    op.create_table(
        "return_lines",
        sa.Column("return_id", sa.BigInteger(), nullable=False),
        sa.Column("sale_line_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("package_id", sa.BigInteger(), nullable=False),
        sa.Column("package_name", sa.String(length=50), nullable=False),
        sa.Column("package_factor", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("quantity_packages", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("quantity_base", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("is_economic", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_physical", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("refund_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=True),
        sa.Column("stock_movement_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], name=op.f("fk_return_lines_lot_id_lots")),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["product_packages.id"],
            name=op.f("fk_return_lines_package_id_product_packages"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_return_lines_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["return_id"], ["returns.id"], name=op.f("fk_return_lines_return_id_returns")
        ),
        sa.ForeignKeyConstraint(
            ["sale_line_id"],
            ["sale_lines.id"],
            name=op.f("fk_return_lines_sale_line_id_sale_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["stock_movement_id"],
            ["stock_movements.id"],
            name=op.f("fk_return_lines_stock_movement_id_stock_movements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_return_lines")),
    )
    op.create_index(
        op.f("ix_return_lines_product_id"), "return_lines", ["product_id"], unique=False
    )
    op.create_index(op.f("ix_return_lines_return_id"), "return_lines", ["return_id"], unique=False)
    op.create_index(
        op.f("ix_return_lines_sale_line_id"), "return_lines", ["sale_line_id"], unique=False
    )
    op.add_column(
        "sale_lines",
        sa.Column(
            "quantity_returned",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

    _seed_permissions()


def _seed_permissions() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.insert(_permissions),
        [{"key": p.key, "description": p.description} for p in PHASE_14_PERMISSIONS],
    )
    permission_ids = dict(
        connection.execute(sa.select(_permissions.c.key, _permissions.c.id)).all()
    )
    role_ids = dict(connection.execute(sa.select(_roles.c.name, _roles.c.id)).all())

    grants = [
        {"role_id": role_ids[role_name], "permission_id": permission_ids[key]}
        for role_name, keys in PHASE_14_ROLE_GRANTS.items()
        for key in keys
    ]
    if grants:
        connection.execute(sa.insert(_role_permissions), grants)


def downgrade() -> None:
    _unseed_permissions()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sale_lines", "quantity_returned")
    op.drop_index(op.f("ix_return_lines_sale_line_id"), table_name="return_lines")
    op.drop_index(op.f("ix_return_lines_return_id"), table_name="return_lines")
    op.drop_index(op.f("ix_return_lines_product_id"), table_name="return_lines")
    op.drop_table("return_lines")
    op.drop_index(op.f("ix_returns_sale_id"), table_name="returns")
    op.drop_table("returns")
    # ### end Alembic commands ###


def _unseed_permissions() -> None:
    connection = op.get_bind()
    keys = [p.key for p in PHASE_14_PERMISSIONS]

    permission_ids = [
        row[0]
        for row in connection.execute(
            sa.select(_permissions.c.id).where(_permissions.c.key.in_(keys))
        ).all()
    ]
    if permission_ids:
        connection.execute(
            _role_permissions.delete().where(_role_permissions.c.permission_id.in_(permission_ids))
        )
        connection.execute(_permissions.delete().where(_permissions.c.id.in_(permission_ids)))
