"""phase 4: pricing

Revision ID: 3c00d4e8913b
Revises: 911bc003c81e
Create Date: 2026-08-08 00:59:54.719327+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.rbac.permissions import PHASE_4_PERMISSIONS, PHASE_4_ROLE_GRANTS

revision: str = "3c00d4e8913b"
down_revision: str | None = "911bc003c81e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Lightweight table handles for the seed data below — see the phase 1
# migration for why these aren't the ORM models.
_permissions = sa.table(
    "permissions",
    sa.column("id", sa.BigInteger),
    sa.column("key", sa.String),
    sa.column("description", sa.String),
)
_roles = sa.table("roles", sa.column("id", sa.BigInteger), sa.column("name", sa.String))
_role_permissions = sa.table(
    "role_permissions",
    sa.column("role_id", sa.BigInteger),
    sa.column("permission_id", sa.BigInteger),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_price_history",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("surcharge_rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("margin_rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("price_formula", sa.String(length=500), nullable=True),
        sa.Column("list_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_price_history_product_id_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_price_history")),
    )
    op.create_index(
        op.f("ix_product_price_history_product_id"),
        "product_price_history",
        ["product_id"],
        unique=False,
    )
    op.add_column(
        "products",
        sa.Column(
            "surcharge_rate", sa.Numeric(precision=18, scale=6), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "margin_rate", sa.Numeric(precision=18, scale=6), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###

    _seed_permissions()


def _seed_permissions() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.insert(_permissions),
        [{"key": p.key, "description": p.description} for p in PHASE_4_PERMISSIONS],
    )
    permission_ids = dict(
        connection.execute(sa.select(_permissions.c.key, _permissions.c.id)).all()
    )
    role_ids = dict(connection.execute(sa.select(_roles.c.name, _roles.c.id)).all())

    grants = [
        {"role_id": role_ids[role_name], "permission_id": permission_ids[key]}
        for role_name, keys in PHASE_4_ROLE_GRANTS.items()
        for key in keys
    ]
    if grants:
        connection.execute(sa.insert(_role_permissions), grants)


def downgrade() -> None:
    _unseed_permissions()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "margin_rate")
    op.drop_column("products", "surcharge_rate")
    op.drop_index(op.f("ix_product_price_history_product_id"), table_name="product_price_history")
    op.drop_table("product_price_history")
    # ### end Alembic commands ###


def _unseed_permissions() -> None:
    connection = op.get_bind()
    keys = [p.key for p in PHASE_4_PERMISSIONS]

    permission_ids = [
        row[0]
        for row in connection.execute(
            sa.select(_permissions.c.id).where(_permissions.c.key.in_(keys))
        ).all()
    ]
    if permission_ids:
        connection.execute(
            _role_permissions.delete().where(_role_permissions.c.permission_id.in_(permission_ids))
        )
        connection.execute(_permissions.delete().where(_permissions.c.id.in_(permission_ids)))
