"""phase 10: pos categories

Revision ID: 6682eb0bfca8
Revises: 77605c60bee5
Create Date: 2026-08-08 02:06:16.030730+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.rbac.permissions import PHASE_10_PERMISSIONS, PHASE_10_ROLE_GRANTS

revision: str = "6682eb0bfca8"
down_revision: str | None = "77605c60bee5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Lightweight table handles for the seed data below — see the phase 1
# migration for why these aren't the ORM models.
_permissions = sa.table(
    "permissions",
    sa.column("id", sa.BigInteger),
    sa.column("key", sa.String),
    sa.column("description", sa.String),
)
_roles = sa.table("roles", sa.column("id", sa.BigInteger), sa.column("name", sa.String))
_role_permissions = sa.table(
    "role_permissions",
    sa.column("role_id", sa.BigInteger),
    sa.column("permission_id", sa.BigInteger),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pos_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=7), server_default="#64748b", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pos_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_pos_categories_name")),
    )
    op.create_index(
        op.f("ix_pos_categories_display_order"), "pos_categories", ["display_order"], unique=False
    )
    op.add_column("products", sa.Column("pos_category_id", sa.BigInteger(), nullable=True))
    op.add_column(
        "products", sa.Column("pos_display_order", sa.Integer(), server_default="0", nullable=False)
    )
    op.create_index(
        op.f("ix_products_pos_category_id"), "products", ["pos_category_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_products_pos_category_id_pos_categories"),
        "products",
        "pos_categories",
        ["pos_category_id"],
        ["id"],
    )
    # ### end Alembic commands ###

    _seed_permissions()


def _seed_permissions() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.insert(_permissions),
        [{"key": p.key, "description": p.description} for p in PHASE_10_PERMISSIONS],
    )
    permission_ids = dict(
        connection.execute(sa.select(_permissions.c.key, _permissions.c.id)).all()
    )
    role_ids = dict(connection.execute(sa.select(_roles.c.name, _roles.c.id)).all())

    grants = [
        {"role_id": role_ids[role_name], "permission_id": permission_ids[key]}
        for role_name, keys in PHASE_10_ROLE_GRANTS.items()
        for key in keys
    ]
    if grants:
        connection.execute(sa.insert(_role_permissions), grants)


def downgrade() -> None:
    _unseed_permissions()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_products_pos_category_id_pos_categories"), "products", type_="foreignkey"
    )
    op.drop_index(op.f("ix_products_pos_category_id"), table_name="products")
    op.drop_column("products", "pos_display_order")
    op.drop_column("products", "pos_category_id")
    op.drop_index(op.f("ix_pos_categories_display_order"), table_name="pos_categories")
    op.drop_table("pos_categories")
    # ### end Alembic commands ###


def _unseed_permissions() -> None:
    connection = op.get_bind()
    keys = [p.key for p in PHASE_10_PERMISSIONS]

    permission_ids = [
        row[0]
        for row in connection.execute(
            sa.select(_permissions.c.id).where(_permissions.c.key.in_(keys))
        ).all()
    ]
    if permission_ids:
        connection.execute(
            _role_permissions.delete().where(_role_permissions.c.permission_id.in_(permission_ids))
        )
        connection.execute(_permissions.delete().where(_permissions.c.id.in_(permission_ids)))
