"""phase 20: performance indexes

No new tables, columns or permissions — three ``status`` columns that were
missing an index despite being the standard filter on tables that only
ever grow: ``sales`` (the POS "resume or open a draft" lookup and every
dashboard metric), ``purchase_orders`` (``GET /purchase-orders?status=``),
and ``outbox_messages`` (the worker's ``FOR UPDATE SKIP LOCKED`` claim
query — the single hottest query in the app).

Revision ID: 89da0848671d
Revises: c63102553dd7
Create Date: 2026-08-08 12:40:32.719709+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "89da0848671d"
down_revision: str | None = "c63102553dd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_outbox_messages_status"), "outbox_messages", ["status"], unique=False)
    op.create_index(op.f("ix_purchase_orders_status"), "purchase_orders", ["status"], unique=False)
    op.create_index(op.f("ix_sales_status"), "sales", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_status"), table_name="sales")
    op.drop_index(op.f("ix_purchase_orders_status"), table_name="purchase_orders")
    op.drop_index(op.f("ix_outbox_messages_status"), table_name="outbox_messages")
    # ### end Alembic commands ###
