"""units display_order

Revision ID: 2e0cee840846
Revises: 20412e4e301c
Create Date: 2026-08-09 15:20:32.899490+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2e0cee840846"
down_revision: str | None = "20412e4e301c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "units", sa.Column("display_order", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "display_order")
    # ### end Alembic commands ###
