"""phase 7: inventory ledger

Revision ID: b10c54df868a
Revises: 586da6716605
Create Date: 2026-08-08 01:26:25.126982+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.rbac.permissions import PHASE_7_PERMISSIONS, PHASE_7_ROLE_GRANTS

revision: str = "b10c54df868a"
down_revision: str | None = "586da6716605"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Lightweight table handles for the seed data below — see the phase 1
# migration for why these aren't the ORM models.
_permissions = sa.table(
    "permissions",
    sa.column("id", sa.BigInteger),
    sa.column("key", sa.String),
    sa.column("description", sa.String),
)
_roles = sa.table("roles", sa.column("id", sa.BigInteger), sa.column("name", sa.String))
_role_permissions = sa.table(
    "role_permissions",
    sa.column("role_id", sa.BigInteger),
    sa.column("permission_id", sa.BigInteger),
)
_warehouses = sa.table("warehouses", sa.column("id", sa.BigInteger), sa.column("name", sa.String))
_locations = sa.table(
    "locations",
    sa.column("id", sa.BigInteger),
    sa.column("warehouse_id", sa.BigInteger),
    sa.column("name", sa.String),
)

#: A single-store deployment (this project's whole premise) needs somewhere
#: for stock to live from the moment phase 9/11/12 start moving it — there
#: is no setup wizard phase, so a default warehouse/location is reference
#: data, seeded here exactly like the phase 1 roles. An operator can add
#: more via the API at any time.
_DEFAULT_WAREHOUSE = "Tienda principal"
_DEFAULT_LOCATION = "Almacén"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "warehouses",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("name", name=op.f("uq_warehouses_name")),
    )
    op.create_table(
        "locations",
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], name=op.f("fk_locations_warehouse_id_warehouses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("warehouse_id", "name", name="uq_locations_warehouse_id_name"),
    )
    op.create_index(op.f("ix_locations_warehouse_id"), "locations", ["warehouse_id"], unique=False)
    op.create_table(
        "stock_balance",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_stock_balance_location_id_locations")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_stock_balance_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_balance_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_balance")),
        sa.UniqueConstraint(
            "product_id",
            "warehouse_id",
            "location_id",
            name="uq_stock_balance_product_warehouse_location",
        ),
    )
    op.create_index(
        op.f("ix_stock_balance_location_id"), "stock_balance", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_balance_product_id"), "stock_balance", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_balance_warehouse_id"), "stock_balance", ["warehouse_id"], unique=False
    )
    op.create_table(
        "stock_movements",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("movement_type", sa.String(length=20), nullable=False),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.BigInteger(), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_stock_movements_location_id_locations")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_stock_movements_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_stock_movements_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_movements_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
    )
    op.create_index(
        op.f("ix_stock_movements_location_id"), "stock_movements", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_movement_type"), "stock_movements", ["movement_type"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_product_id"), "stock_movements", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_warehouse_id"), "stock_movements", ["warehouse_id"], unique=False
    )
    # ### end Alembic commands ###

    _seed_permissions()
    _seed_default_warehouse()


def _seed_permissions() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.insert(_permissions),
        [{"key": p.key, "description": p.description} for p in PHASE_7_PERMISSIONS],
    )
    permission_ids = dict(
        connection.execute(sa.select(_permissions.c.key, _permissions.c.id)).all()
    )
    role_ids = dict(connection.execute(sa.select(_roles.c.name, _roles.c.id)).all())

    grants = [
        {"role_id": role_ids[role_name], "permission_id": permission_ids[key]}
        for role_name, keys in PHASE_7_ROLE_GRANTS.items()
        for key in keys
    ]
    if grants:
        connection.execute(sa.insert(_role_permissions), grants)


def _seed_default_warehouse() -> None:
    connection = op.get_bind()
    warehouse_id = connection.execute(
        sa.insert(_warehouses).returning(_warehouses.c.id), {"name": _DEFAULT_WAREHOUSE}
    ).scalar_one()
    connection.execute(
        sa.insert(_locations), {"warehouse_id": warehouse_id, "name": _DEFAULT_LOCATION}
    )


def downgrade() -> None:
    _unseed_permissions()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_movements_warehouse_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_product_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_movement_type"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_location_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_stock_balance_warehouse_id"), table_name="stock_balance")
    op.drop_index(op.f("ix_stock_balance_product_id"), table_name="stock_balance")
    op.drop_index(op.f("ix_stock_balance_location_id"), table_name="stock_balance")
    op.drop_table("stock_balance")
    op.drop_index(op.f("ix_locations_warehouse_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_table("warehouses")
    # ### end Alembic commands ###


def _unseed_permissions() -> None:
    connection = op.get_bind()
    keys = [p.key for p in PHASE_7_PERMISSIONS]

    permission_ids = [
        row[0]
        for row in connection.execute(
            sa.select(_permissions.c.id).where(_permissions.c.key.in_(keys))
        ).all()
    ]
    if permission_ids:
        connection.execute(
            _role_permissions.delete().where(_role_permissions.c.permission_id.in_(permission_ids))
        )
        connection.execute(_permissions.delete().where(_permissions.c.id.in_(permission_ids)))
