"""phase 8: lots

Revision ID: 70fc407a2e6d
Revises: b10c54df868a
Create Date: 2026-08-08 01:43:57.899872+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.rbac.permissions import PHASE_8_PERMISSIONS, PHASE_8_ROLE_GRANTS

revision: str = "70fc407a2e6d"
down_revision: str | None = "b10c54df868a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Lightweight table handles for the seed data below — see the phase 1
# migration for why these aren't the ORM models.
_permissions = sa.table(
    "permissions",
    sa.column("id", sa.BigInteger),
    sa.column("key", sa.String),
    sa.column("description", sa.String),
)
_roles = sa.table("roles", sa.column("id", sa.BigInteger), sa.column("name", sa.String))
_role_permissions = sa.table(
    "role_permissions",
    sa.column("role_id", sa.BigInteger),
    sa.column("permission_id", sa.BigInteger),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lots",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("lot_number", sa.String(length=100), nullable=False),
        sa.Column("manufacturing_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("supplier_id", sa.BigInteger(), nullable=True),
        sa.Column("purchase_order_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_lots_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_lots_purchase_order_id_purchase_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_lots_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lots")),
        sa.UniqueConstraint("product_id", "lot_number", name="uq_lots_product_id_lot_number"),
    )
    op.create_index(op.f("ix_lots_expiration_date"), "lots", ["expiration_date"], unique=False)
    op.create_index(op.f("ix_lots_product_id"), "lots", ["product_id"], unique=False)
    op.add_column("stock_balance", sa.Column("lot_id", sa.BigInteger(), nullable=True))
    op.drop_constraint(
        op.f("uq_stock_balance_product_warehouse_location"), "stock_balance", type_="unique"
    )
    op.create_index(op.f("ix_stock_balance_lot_id"), "stock_balance", ["lot_id"], unique=False)
    op.create_index(
        "uq_stock_balance_no_lot",
        "stock_balance",
        ["product_id", "warehouse_id", "location_id"],
        unique=True,
        postgresql_where=sa.text("lot_id IS NULL"),
    )
    op.create_index(
        "uq_stock_balance_with_lot",
        "stock_balance",
        ["product_id", "warehouse_id", "location_id", "lot_id"],
        unique=True,
        postgresql_where=sa.text("lot_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_stock_balance_lot_id_lots"), "stock_balance", "lots", ["lot_id"], ["id"]
    )
    op.add_column("stock_movements", sa.Column("lot_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_stock_movements_lot_id"), "stock_movements", ["lot_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_stock_movements_lot_id_lots"), "stock_movements", "lots", ["lot_id"], ["id"]
    )
    # ### end Alembic commands ###

    _seed_permissions()


def _seed_permissions() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.insert(_permissions),
        [{"key": p.key, "description": p.description} for p in PHASE_8_PERMISSIONS],
    )
    permission_ids = dict(
        connection.execute(sa.select(_permissions.c.key, _permissions.c.id)).all()
    )
    role_ids = dict(connection.execute(sa.select(_roles.c.name, _roles.c.id)).all())

    grants = [
        {"role_id": role_ids[role_name], "permission_id": permission_ids[key]}
        for role_name, keys in PHASE_8_ROLE_GRANTS.items()
        for key in keys
    ]
    if grants:
        connection.execute(sa.insert(_role_permissions), grants)


def downgrade() -> None:
    _unseed_permissions()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_stock_movements_lot_id_lots"), "stock_movements", type_="foreignkey"
    )
    op.drop_index(op.f("ix_stock_movements_lot_id"), table_name="stock_movements")
    op.drop_column("stock_movements", "lot_id")
    op.drop_constraint(op.f("fk_stock_balance_lot_id_lots"), "stock_balance", type_="foreignkey")
    op.drop_index(
        "uq_stock_balance_with_lot",
        table_name="stock_balance",
        postgresql_where=sa.text("lot_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_stock_balance_no_lot",
        table_name="stock_balance",
        postgresql_where=sa.text("lot_id IS NULL"),
    )
    op.drop_index(op.f("ix_stock_balance_lot_id"), table_name="stock_balance")
    op.create_unique_constraint(
        op.f("uq_stock_balance_product_warehouse_location"),
        "stock_balance",
        ["product_id", "warehouse_id", "location_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("stock_balance", "lot_id")
    op.drop_index(op.f("ix_lots_product_id"), table_name="lots")
    op.drop_index(op.f("ix_lots_expiration_date"), table_name="lots")
    op.drop_table("lots")
    # ### end Alembic commands ###


def _unseed_permissions() -> None:
    connection = op.get_bind()
    keys = [p.key for p in PHASE_8_PERMISSIONS]

    permission_ids = [
        row[0]
        for row in connection.execute(
            sa.select(_permissions.c.id).where(_permissions.c.key.in_(keys))
        ).all()
    ]
    if permission_ids:
        connection.execute(
            _role_permissions.delete().where(_role_permissions.c.permission_id.in_(permission_ids))
        )
        connection.execute(_permissions.delete().where(_permissions.c.id.in_(permission_ids)))
