"""phase 11: sales

Revision ID: 2573ff5a5eb7
Revises: 6682eb0bfca8
Create Date: 2026-08-08 02:16:29.716464+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.rbac.permissions import PHASE_11_PERMISSIONS, PHASE_11_ROLE_GRANTS

revision: str = "2573ff5a5eb7"
down_revision: str | None = "6682eb0bfca8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Lightweight table handles for the seed data below — see the phase 1
# migration for why these aren't the ORM models.
_permissions = sa.table(
    "permissions",
    sa.column("id", sa.BigInteger),
    sa.column("key", sa.String),
    sa.column("description", sa.String),
)
_roles = sa.table("roles", sa.column("id", sa.BigInteger), sa.column("name", sa.String))
_role_permissions = sa.table(
    "role_permissions",
    sa.column("role_id", sa.BigInteger),
    sa.column("permission_id", sa.BigInteger),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales",
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=False),
        sa.Column("cashier_user_id", sa.BigInteger(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cashier_user_id"], ["users.id"], name=op.f("fk_sales_cashier_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_sales_location_id_locations")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], name=op.f("fk_sales_warehouse_id_warehouses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
    )
    op.create_index(op.f("ix_sales_warehouse_id"), "sales", ["warehouse_id"], unique=False)
    op.create_table(
        "sale_lines",
        sa.Column("sale_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("package_id", sa.BigInteger(), nullable=False),
        sa.Column("package_name", sa.String(length=50), nullable=False),
        sa.Column("package_factor", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("quantity_packages", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("quantity_base", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("discount_rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["product_packages.id"],
            name=op.f("fk_sale_lines_package_id_product_packages"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_sale_lines_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"], ["sales.id"], name=op.f("fk_sale_lines_sale_id_sales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_lines")),
    )
    op.create_index(op.f("ix_sale_lines_product_id"), "sale_lines", ["product_id"], unique=False)
    op.create_index(op.f("ix_sale_lines_sale_id"), "sale_lines", ["sale_id"], unique=False)
    # ### end Alembic commands ###

    _seed_permissions()


def _seed_permissions() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.insert(_permissions),
        [{"key": p.key, "description": p.description} for p in PHASE_11_PERMISSIONS],
    )
    permission_ids = dict(
        connection.execute(sa.select(_permissions.c.key, _permissions.c.id)).all()
    )
    role_ids = dict(connection.execute(sa.select(_roles.c.name, _roles.c.id)).all())

    grants = [
        {"role_id": role_ids[role_name], "permission_id": permission_ids[key]}
        for role_name, keys in PHASE_11_ROLE_GRANTS.items()
        for key in keys
    ]
    if grants:
        connection.execute(sa.insert(_role_permissions), grants)


def downgrade() -> None:
    _unseed_permissions()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sale_lines_sale_id"), table_name="sale_lines")
    op.drop_index(op.f("ix_sale_lines_product_id"), table_name="sale_lines")
    op.drop_table("sale_lines")
    op.drop_index(op.f("ix_sales_warehouse_id"), table_name="sales")
    op.drop_table("sales")
    # ### end Alembic commands ###


def _unseed_permissions() -> None:
    connection = op.get_bind()
    keys = [p.key for p in PHASE_11_PERMISSIONS]

    permission_ids = [
        row[0]
        for row in connection.execute(
            sa.select(_permissions.c.id).where(_permissions.c.key.in_(keys))
        ).all()
    ]
    if permission_ids:
        connection.execute(
            _role_permissions.delete().where(_role_permissions.c.permission_id.in_(permission_ids))
        )
        connection.execute(_permissions.delete().where(_permissions.c.id.in_(permission_ids)))
